DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS limb;
DROP TABLE IF EXISTS corpse;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE limb (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER,
  corpse_id INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (corpse_id) REFERENCES corpse (id)
);

CREATE TABLE corpse (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
